### PR TITLE
Additional network supports + Init image attempt

### PR DESCRIPTION
**Pull request by huxiuhan**
Support multiple Lora networks instead of just one.
Add a test case in README.
Git ignore model files and generated results.
sample

### CODE REVIEW

**Comment by huxiuhan** [comment]
Added Init Image Attempt Case

Init image as init latent:
init_image

Results:
sample

**Comment by guoyww** [comment]
Thanks for your contributions, and we love your experiment on image initialization😊

Currently, we hope this repo aligns with our Arxiv report (adding too many features may confuse the readers). We would consider incorporating your feature in our later version (webui extension, etc.).

Btw, we would like to add your amazing samples to the gallery in our readme, would you please make a separate pr to update the README.md?

**Comment by itsagoodbrain** [comment]
Might I suggest having a dev fork so development of features for the future versions stays integrated in your main repo while maintaining consistency with the Arxiv paper.

**Comment by huxiuhan** [comment]
> Thanks for your contributions, and we love your experiment on image initialization😊
> 
> Currently, we hope this repo aligns with our Arxiv report (adding too many features may confuse the readers). We would consider incorporating your feature in our later version (webui extension, etc.).
> 
> Btw, we would like to add your amazing samples to the gallery in our readme, would you please make a separate pr to update the README.md?

Sure, glad to contribute.

**Pull request closed without merging**
