### PR TITLE
Gradio WebUI Completed

### PR DESCRIPTION
**Pull request by x-CK-x**
I made a gradio interface to align with all the features as demonstrated in the paper.
I also made plenty of configurable options for the user to edit the prompt yaml through the UI.
I added two pip requirements & created an example/demo of the interface on the readme.

I hope this helps.

### CODE REVIEW

**Comment by guoyww** [comment]
Thanks for your contribution! After testing, we will merge this PR to the main repo, thanks.

**Comment by x-CK-x** [comment]
I would also be glad to add to the UI, to support any _community_ features placed in the other branch mentioned in the readme if you would like?
I could make that a separate PR for that _community contributions_ branch when it gets created.

**Comment by x-CK-x** [comment]
Also are there any additional LoRA, CLIP, and/or sampler options you would like me to add to the UI?

e.g. the list I've compiled so far might include:
- a single-select dropdown menu for different samplers (I'm not sure if you have preference of which ones should be available though?)
- a multi-select dropdown menu to enable any of the below options:
    - clip_skip
    - rank
    - lora_alpha
    - target_modules
    - bias
    - layers_to_transform
    - layers_pattern
- the gradio Accordian component to display any enabled parameter to be configured as necessary

**Comment by x-CK-x** [comment]
I edited the PR to point to the dev branch instead, but I was wondering @guoyww what features do you want per se?
I can work on the UI in app.py instead, but idk of what I mentioned is actually desired. And what features from webui.py if any are desired to be merged in with app.py?

and is the dev branch the Official community contributions branch?

~thanks

**Comment by guoyww** [comment]
Yes, the `dev` branch is for community contributions.

I suppose basic features like more sampler types, multi-LoRA models, and textual embedding are desired for both `app.py` and `webui.py`.

Also, since someone has contributed an A1111 extension, which may be used more frequently, the Gradio demo in this repo may not need too many complex features.

**Pull request merged**
